name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install 🔧
        run: yarn install

      - name: Build 🧱
        run: yarn build

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install requirements
        run: pip install -r jinja2

      - name: Update about.md
        run: python scripts/gen_index.py content

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Push changes ⬆️
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish'
          force-add: 'true'
          rebase: 'true'
          email: 'kiennt2609@gmail.com'
          name: 'Kien Nguyen-Tuan'
